apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-ln6l
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-ln6l
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-ln6l
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-ln6l
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-ln6l
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-ln6l@sha256:13733568b1567dcf7809e10d94f2665913b8672b3271a82931d91a799f7e5ad9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
